### ISSUE TITLE
Please support PHP 8.0

### ISSUE THREAD

**Issue by anomiex** [sirbrillig/phpcs-changed#36]
It looks like your PHPUnit tests all pass once dependencies are updated. You'll have some new PHPStan warnings to fix though.

Assuming you don't want to drop support for PHP 7.1, you'll need the following:

* dealerdirect/phpcodesniffer-composer-installer to 0.7.1, which supports all relevant PHP versions.
* phpunit/phpunit needs at most ^7.5 to continue supporting PHP 7.1, while ^9.3 is needed for PHP 8.0. Your tests themselves seem happy to run with either, so `"^6.4 || ^9.5"` would work.
* phpstan/phpstan to 0.12.33+, which supports all the relevant PHP versions.
* limedeck/phpunit-detailed-printer is somewhat problematic because it doesn't declare its dependencies correctly. You need ^3.1 for PHPUnit 6.4 and ^6.0 for PHPUnit 9, but declaring `"^3.1 || ^6.0"` will install 6.0 along with PHPUnit 6.4 because LimeDeck doesn't declare its own PHPUnit dependency properly.
* Your sirbrillig/phpcs-import-detection needs dependency updates to support PHP 8 too.
    * dealerdirect/phpcodesniffer-composer-installer to 0.7.1 again.
    * phpunit/phpunit again passes all tests with `"^6.5 || ^9.0"`.
    * limedeck/phpunit-detailed-printer has the same issue.

I haven't checked whether you have any code not covered by your tests.

**Comment by sirbrillig** [comment]
Thank you for the detailed investigation! I'm just getting around to preparing various things for PHP 8. I can easily get rid of `phpunit-detailed-printer` (here and in my other projects) to simplify things.

I'm wondering what the appropriate thing to do is for phpcs-changed, though because phpcs itself doesn't seem ready to support it, as discussed in this issue: https://github.com/squizlabs/PHP_CodeSniffer/issues/3182 I suppose I could update this code as you suggest since technically there is not reason it shouldn't work if phpcs does. Giving it a shot...
